POST http://localhost:3001/api/customers
Content-Type: application/json

{
    "username": "jane.smith",
    "name": "Jane Smith",
    "email": "jane.smith@example.com",
    "phone": "9988776655",
    "password": "1234"
}